const COMPLAINT_STATUS = {
	NOT_VERIFIED: "NOT_VERIFIED",
	VERIFIED: "VERIFIED",
	COMPLETED: "COMPLETED",
};

const VALIDATION_STATUS = {
	FORWARDED: "FORWARDED",
	REJECTED: "REJECTED",
};

export { COMPLAINT_STATUS, VALIDATION_STATUS };
